### ISSUE TITLE
Runtime errors på gamle anbefalinger

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#1]
Alle anbefalinger importeret fra det gamle system har “Runtime Error” pga. problemer med visning af billede. Hvis billede uploades til anbefalingen igen, er problemet væk.

**Comment by terkellarsen** [comment]
Fixet / dev og live

**Comment by kristianbanghansen** [comment]
Det virker. Hvor er det bare fantastisk dejligt!
