### ISSUE TITLE
Link til guest writer virker ikke

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#100]
I umbracos "guest writer"-fane er der et felt, hvor vi indtaster link til gæsteskribentens personlige side. Dette link er pt. ikke tilgængeligt på hjemmesiden. 

Eksempel her (klik på skribentens navn):
http://www.thisisodense.dk/da/3847/et-droemmekompagni-sidste-udstilling-paa-organon

![image](https://user-images.githubusercontent.com/23633076/69286262-1249b400-0bf3-11ea-9f73-4f9a11e6c407.png)

**Comment by mimse** [comment]
@kristianbanghansen det skulle virke nu :-)
