### ISSUE TITLE
Ny type side

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#13]
Der skal oprettes en type underside, der ligner forsiden, men hvor anbefalinger vises og filtereres på baggrund af “writer” eller “location” i stedet for dato. Klik på antal anbefalinger skal føre til denne type side. (altså fx en side, der viser alle de anbefalinger Bo har skrevet, eller en side, der viser alle de anbefalinger, der er lavet af Jazzhus Dexter)

**Comment by kristianbanghansen** [comment]
Hører under issue #27
