### ISSUE TITLE
Problemer med billeder i linkdelinger på Facebook

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#14]
Indstille og:image, så facebook vælger ikke vælger et af “læs mere”-ikonerne i bunden af siden til linkvisninger.

**Comment by kristianbanghansen** [comment]
Facebooks debug-værktøj kan give mange informationer om, hvad der skal forbedres. https://developers.facebook.com/tools/debug/

**Comment by terkellarsen** [comment]
Fixet dev. Kan ikke testes der:
Jeg definerer billedet i en data-media-attribut inkl. domæne. Facebook henter en version af billedet, når man deler, så det kan ikke testes på dev og stage, da Facebook ikke har adgang til at hente fra disse.

**Comment by kristianbanghansen** [comment]
Fantastisk. Det er vi mange, der bliver glade for. Og jeg slipper forhåbentlig for ugentlige besøg hos Facebooks Open Graph Debugger ;-). Sig til, når det er live.

**Comment by terkellarsen** [comment]
Det er live.

**Comment by terkelskibbylarsen** [comment]
Har tilføjet facebook crop. Facebook-share-debuggeren bliver dog stadig ved melde tilfældige fejl.
