### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#16]
I detaljevisning af engelske recommendations skal tilføjes “Translated by: “ i infolinjen. Oversætternavnet er en relation med property “translator”.

**Comment by terkellarsen** [comment]
@mimse - Hvordan vil du have strukturen? Som Writer hvor jeg tilføjer TranslatorName, TranslatorUrl til RecommendationUKModel.

**Comment by kristianbanghansen** [comment]
#43

**Comment by terkellarsen** [comment]
Fixet dev

**Comment by kristianbanghansen** [comment]
Jeg kan ikke se oversætternavnet her: https://dev-this-is-odense.s1.umbraco.io/en/7541/one-of-denmarks-best-chefs-goes-to-spis eller her: https://dev-this-is-odense.s1.umbraco.io/en/7572/vegan-day

**Comment by terkellarsen** [comment]
Fixet dev
