### ISSUE TITLE
Text overlay på iphone ved skribenter

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#18]
Text-overlay på skribentbillederne virker ikke på iPhone, men link til “læs mere” virker alligevel, hvis man trykker nederst i højre hjørne, selvom man ikke kan se linkteksten.

**Comment by kristianbanghansen** [comment]
Dette er et højt prioriteret issue

**Comment by terkellarsen** [comment]
Fixet, tilføjede også lidt padding, da teksten stod helt ud til kanten af boksen.

**Comment by kristianbanghansen** [comment]
Det virker stadig ikke på min iPhone. Har du et screenshot, hvor det virker?
Vi er enige om, at tex-overlayet med halvgennemsigtig blå baggrund skal vise sig ved berøring på billederne, når nu a:hover ikke virker på smartphones. @terkellarsen

**Comment by terkellarsen** [comment]
Når jeg committer koden, så ryger det vist kun til et test-site.
Jeg har midlertidigt lagt en kopi [her](http://tio.regard.dk/da/about): - linket virker til i morgen tidlig.

**Comment by kristianbanghansen** [comment]
Fedt! Det virker

**Comment by kristianbanghansen** [comment]
Det virker ikke nu

**Comment by terkellarsen** [comment]
Er det her du kigger: https://dev-this-is-odense.s1.umbraco.io/da/about

Der kommer info fint op, når jeg prøver.

**Comment by kristianbanghansen** [comment]
Ah, sorry. Jeg troede det var deployed til live. 👍🏼
