### ISSUE TITLE
Rette farven på maps-pinnen for nature/activities

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#22]
Hvilke farver?

**Comment by kristianbanghansen** [comment]
https://cloud.githubusercontent.com/assets/23633076/21119827/91f09e76-c0c4-11e6-9f18-d173abd8603b.PNG

Her kan du se forskellen i farverne. De skal på en måde kobles til samme globale farveskema, som vi kan ændre på, hvert år, når vi udgiver en ny byguide.
