### ISSUE TITLE
Smartere åbningstider

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#24]
Smartere visning af åbningstider i places. Se php-kode her: http://codepad.org/ALhReLdG

**Comment by terkellarsen** [comment]
Fixet
https://dev-this-is-odense.s1.umbraco.io/da/place/2352/dr-adams

**Comment by kristianbanghansen** [comment]
Det virker overordnet set rigtig godt, men der sker fejl i nogle grænsetilfælde:

Brandts13:
Man - Tir:  - 
_Ons - Søn: 10.00 - 17.00_
Tor: 12.00 - 21.00

No. 61:
_Man - Søn:  -_ 
Tir - Lør: 17.00 - 24.00

StudieStuen:
_Man - Fre: 10.00 - 18.00_
Tir - Tor: 10.00 - 21.00
Lør - Søn: 10.00 - 16.00

Dage skal altså ikke grupperes, hvis der er mellemliggende dage med ikke-identiske åbningstider.

**Comment by terkellarsen** [comment]
Så bliver dagene liste i rækkefølge:
https://dev-this-is-odense.s1.umbraco.io/en/place/2385/brandts-13
https://dev-this-is-odense.s1.umbraco.io/en/place/2418/no-61
https://dev-this-is-odense.s1.umbraco.io/en/place/2456/studiestuen

**Comment by kristianbanghansen** [comment]
Det virker perfekt! Stærkt gået
