### ISSUE TITLE
Arkiv funktion

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#27]
Et komplet arkiv med alle tidligere ugers anbefalinger med mulighed for filtrering og sortering. Illustration her: https://docs.google.com/document/d/1T5U6YWgKWKVxe-An9rziBAgrTBtFgFfqd_8-o3CYFsc/edit

**Comment by kristianbanghansen** [comment]
Første skridt er, at lave et standard layout for komplette lister af anbefalinger, der kan tilgås ved unik URL baseret på:
- Skribent (thisisodense.dk/da/writer/morten-hansen + thisisodense.dk/da/places/writer/morten-hansen)
- Location (thisisodense.dk/da/location/jazzhus-dexter)
- Event type (thisisodense.dk/da/category/udstilling)
- Location type (thisisodense.dk/da/places/2/eating) **EKSISTERER ALLEREDE**
- År, uge (thisisodense.dk/da/2016/49)

Listens layout skal bruge vores eksisterende listeview fra forsiden og byguiden, blot uden billeder og share-knapper og med et mere kompakt layout bl.a. med en mindre skriftstørrelse på overskrifterne. Ligesom i den eksisterende detaljevisning af gamle anbefalinger, skal datoen ikke vises til venstre for overskriften, men i stedet som en del af infolinjen. Infolinjen skal også i alle tilfælde indeholde skribentens navn, samt location navn (i stedet for adresse).

To mockups hurtigt lavet i google chrome (dvs. uden alle de ønskede ændringer til layout og infolinje):
https://cloud.githubusercontent.com/assets/23633076/21121441/a7e3449c-c0cc-11e6-82c5-69708f3d0804.PNG
https://cloud.githubusercontent.com/assets/23633076/21121442/a7e69fd4-c0cc-11e6-94be-12f3bd8e8c23.PNG

**Comment by kristianbanghansen** [comment]
Terkel, jeg har givet adgang til googledokumentet, som Morten har linket til her. Vær opmærksom på, at det er en gammel illustration, der ikke nødvendigvis er den rette løsning for os nu. Men tag den inspiration med, som du kan få ud af det.
