### ISSUE TITLE
Dato autoudfyld

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#32]
I formularen for recommendations autoudfyldes sluttid og doors med starttidspunktet. Det skal stoppe.

**Comment by terkellarsen** [comment]
Det kan jeg ikke genskabe.

**Comment by kristianbanghansen** [comment]
I dette eksempel har jeg ikke indtastet nogen tal i formularen, men blot sat cursoren i felterne. (i feltet doors har jeg ikke engang sat min cursor, før det blev udfyldt)

![udklip33](https://cloud.githubusercontent.com/assets/23633076/21568775/8f97c8ba-ceb7-11e6-97a5-e6f28b9dbfc4.PNG)

![udklip34](https://cloud.githubusercontent.com/assets/23633076/21568777/95e0a296-ceb7-11e6-8d1d-af59b280ea27.PNG)

Jeg har faktisk også svært ved at genskabe fejlen, hver gang jeg prøver. Nogle gange er starttid og doors automatisk udfyldt med det aktuelle tidspunkt - andre gange ikke.

Det kan virke som en harmløs automatisk service, men det leder til fejl, hvis skribenten ikke er opmærksom på det. Startdato og starttid er påkrævede felter, så det er fint, at de autoudfyldes. Slutdato, sluttid og doors skal aldrig autoudfyldes, men kun udfyldes manuelt af skribenten, hvis der er behov for det.
