### ISSUE TITLE
Linket "Se hele holdet bag TIO" virker ikke

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#41]
Skribentprofilerne afsluttes med link til "Om This Is Odense"-siden. Linket er brudt fordi, der for nylig er lavet en dansk/engelsk opdeling af om-siden og en ændring af adressen til om-siden.

**Comment by terkellarsen** [comment]
Fixet dev, jeg lagde et anchorpoint ind, så den går til "holdet bag".

**Comment by mimse** [comment]
Testet
