### ISSUE TITLE
Skribent- og oversætternavne i infolinjen

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#43]
Fordi mange uger nu deles mellem flere skribenter og oversættere, er der behov for, at skribentens navn bliver en fast del af infolinjerne på forsiden. Reglen om at navnet på ugens skribent kun skal stå i toppen af forsiden, skal afskaffes.

Desuden skal infolinjen også indeholde oversætterens navn på den engelske forside, samt i detaljevisninger af de engelske anbefalinger.

**Comment by terkellarsen** [comment]
Fixet dev,
Vil I lige kontrollere at gæsteskribent funktionalitet virker som det skal. Tak.

**Comment by mimse** [comment]
![image](https://cloud.githubusercontent.com/assets/1250254/21521976/df1d5ccc-cd01-11e6-9fe3-093e19f93763.png)

Gæste anbefalingen ligger ikke øverst mere

**Comment by kristianbanghansen** [comment]
Jeg kan ikke lide, at skribentnavnet får en ny linje. Efter min vurdering skal den grafiske opsætning af infolinjen forblive, som den er. Ændringen skal blot være, at skribentnavnet altid står der - istedet for idag, hvor det kun står der under særlige betingelser.

**Comment by terkellarsen** [comment]
Linjeskift fjernet foran skribent.

**Comment by kristianbanghansen** [comment]
Jeg kan se, at hjemmesiden ikke længere skriver, hvem der er ugens skribent. Har I fjernet det? Eller ændret reglen for visningen af linjen?

Hvis en skribent har skrevet 4 eller 5 af ugens anbefalinger, så skal linjen ihvertfald vises. Linjen har særligt en funktion, når der er en gæsteskribent og siden opdeles i gæsteskribentens og vores anbefalinger.

Hvis linjen ikke vises, så skal der fjernes noget afstand ned til den første anbefaling. Se her:
![udklip34343](https://cloud.githubusercontent.com/assets/23633076/21661535/d0bac7c2-d2d4-11e6-93ea-da369979d4c0.PNG)

**Comment by mimse** [comment]
Du skrev jo selv at den skulle afskaffes 

>  Reglen om at navnet på ugens skribent kun skal stå i toppen af forsiden, skal afskaffes

**Comment by kristianbanghansen** [comment]
Ja, det man skal hæfte sig I i den sætning er ordet "kun". Jeg beklager, at det kunne misforstås, men men hensigt er at det skal stå begge steder, og ikke kun i toppen.

Mvh Kristian
