### ISSUE TITLE
Facebooks like box fylder ikke hele sidens bredde

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#46]
Dette er et gammelt issue, vi før har talt om. Men der må være en løsning.

Jeg ser tre muligheder:
- Boksen strækkes på en opfindsom måde, så den fylder hele sidens bredde
- Boksen centreres, mens der lægges en passende baggrundsfarve (evt. sort eller facebook-grå) i boksens højde og sidens bredde.
- Boksen suppleres til højre med endnu en boks (idéer: Instagram embed eller løbende hjemmeside-statistik)

![skaermbillede 2016-12-14 kl 23 32 35](https://cloud.githubusercontent.com/assets/23633076/21204219/91aa10f8-c256-11e6-8964-4ada965b316e.png)

**Comment by terkellarsen** [comment]
Fixet, boksen centreres med baggrundsfarve.

**Comment by kristianbanghansen** [comment]
Jeg kan hverken se ændringen i dev eller live. Eller misforstår jeg, når du bare skriver "fixet"?

**Comment by terkellarsen** [comment]
Ctrl + F5 for at reloade.
Det er rettet i style sheet, der bliver cached i browser.

**Comment by kristianbanghansen** [comment]
Det virker i live!

**Comment by kristianbanghansen** [comment]
Løsningen er ser desværre ikke ud til at virke responsivt ift. smalle skærmstørrelser - fx smartphones.

Se nedenfor:
![image1](https://cloud.githubusercontent.com/assets/23633076/21662018/ac8d2d2e-d2d7-11e6-9ccc-639c925e2aa5.PNG)

**Comment by terkelskibbylarsen** [comment]
Fixet dev.
