### ISSUE TITLE
Ny indholdstype "Longreads"

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#47]
Vi skal ikke længere have en separat blog-side, men kunne omfatte den slags indhold på vores egen side. Desuden er det vedtaget i gruppen, at vi i oftere skal bringe denne slags debat- og blogindlæg - måske med en fast vagtplan. Pt. lægges de kun i facebook note-funktion, men vi skal selvfølgelig også have dem på hjemmesiden.

Indholdstypen skal kunne præsentere et rigt indhold med mange indlejrede medietyper og skal have en udgivelsesdato i infolinjen istedet for en arrangementsdato. Desuden intet sted, adresse, arrangør og lignende.

Forsiden for denne indholdstype skal bare vise et langt feed med indlæg sorteret efter udgivelsesdato med nyeste først.

**Comment by kristianbanghansen** [comment]
Jeg har nu oprettet Blog post og Blog repository i Umbraco. Se i dokumenttyper og datatyper samt indlæg her: http://www.thisisodense.dk/umbraco/#/content/content/edit/1076

Visuelt kskal vi bruge layoutet fra Locations, tilpasse ikonet og infolinjen og fjerne de unødvendige dele, som fx åbningstider og bykortet i bunden. I toppen af siden genbruge navigationen fra byguiden, som tager udgangspunkt i WebTagsBlog.

Ikonet fra locations erstattes med en miniature af skribentbilledet, eller alternativt fra gæsteskribent-billedet fra Guest Writer-fanen. Jeg har lavet et nyt crop i "Image Cropper (1)", som hedder miniatureCrop, som skal bruges til dette. Ligesom ved byguidens ikoner, skal højden ligge fast på 47, mens bredden justerer sig responsivt (max 71.391, min 28)

![udklip4](https://cloud.githubusercontent.com/assets/23633076/22975584/9562d164-f387-11e6-84d4-7cb38ad2fbc1.PNG)
![udklip4b](https://cloud.githubusercontent.com/assets/23633076/22975585/956341f8-f387-11e6-9ffe-fda5b883ab60.PNG)

@mimse og @terkellarsen @terkelskibbylarsen

**Comment by kristianbanghansen** [comment]
@terkelskibbylarsen Jeg har opdaget at de fleste af mine ændringer af dokumenttyper og datatyper er gået tabt, fordi jeg ikke har lavet dem på dev-siden. Det har jeg så gjort nu, og har oprettet den første test af et "Longread":
https://dev-this-is-odense.s1.umbraco.io/umbraco/#/content/content/edit/7729

**Comment by mimse** [comment]
Underoverskrevet fjernes, 
billedet af skribent droppes,
Max-with af billedet der er sat ind via article

**Comment by mimse** [comment]
Drop tags

**Comment by mimse** [comment]
Oversætter skal i infolinjen
