### ISSUE TITLE
: on writers main page

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#48]
![image](https://cloud.githubusercontent.com/assets/1250254/21522107/1ad6ae5c-cd03-11e6-86e5-f492c63ea7c0.png)

**Comment by terkellarsen** [comment]
Teksten bliver ikke vist, da den tager fra English (United States), der ikke indeholder en oversættelse.
Sproget kan slettets, så der kun er English og Dansk tilbage. Jeg har gjort det lokalt og har submittet til dev, hvor det også blev fjernet. Så jeg ved ikke hvorfor det er på Stage, hvis sitet er opdateret.

![translate](https://cloud.githubusercontent.com/assets/23321644/21567916/58284c30-ceb0-11e6-9829-bcd49607f933.png)

**Comment by kristianbanghansen** [comment]
Dette issue ser ud til at være fixet.  Jeg ser ingen fejl af denne slags på hverken live eller dev lige nu.
