### ISSUE TITLE
Dato på gamle anbefalinger

### ISSUE THREAD

**Issue by mimse** [thisisodense/tio-web#5]
I anbefalinger fra tidligere uger, hvor dato vises i infolinjen, sker der en fejl, når anbefalingen kun har en startdato (og ikke en slutdato). Så vises slutdatoen som “1. januar 2016”, selvom det ikke er korrekt. Det skal rettes. http://i.imgur.com/MaEGv9a.png

**Comment by terkellarsen** [comment]
I RecommendationModel er der test på om EndDate er sat. Så det ligner det er fixet.
Jeg har ændret i koden, så hvis startdato er lig slutdato vises de ikke som interval.

**Comment by kristianbanghansen** [comment]
Det lyder godt. Husk også at koden skal tage hensyn til, at hvis slutdato ikke er sat, så skal resultatet heller ikke vises som et interval, men blot som startdato.
Slutdato er ikke et påkrævet felt.
