### ISSUE TITLE
Klik på flag nulstiller valgt kategori i byguiden

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#50]
Dette issue ligner et, der lige er rettet for nylig, men fejlen er nu ikke, at brug af byguidens kategorivælger  nulstiller sprogvalget (det fungerer nemlig fint), nej, fejlen er at brug af sprogvælgeren nulstiller kategorivalget.

Eksempel:
Bruger står på: http://www.thisisodense.dk/da/places/36/drinking
Klikker på det britiske flag
Og ender her: http://www.thisisodense.dk/en/places
hvor brugeren rigtigt skulle have endt her: http://www.thisisodense.dk/en/places/36/drinking

Fejlen går begge veje mellem dansk og engelsk

**Comment by terkellarsen** [comment]
Fixet dev

**Comment by kristianbanghansen** [comment]
Løsningen er testet på live, og det virker perfekt.
