### ISSUE TITLE
TIP-OS-knappen skal omdirigeres

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#53]
Linket i sidefoden og på About-siden til "TIP OS" skal omdirigeres til vores messenger-link: http://m.me/ThisIsOdense

**Comment by mimse** [comment]
Vil det ikke give en masse spam?

**Comment by kristianbanghansen** [comment]
Facebook opfordrer folk til at dele deres messenger-link, så jeg tror de
sørger for at sortere spam fra.
Altså, jeg mener ikke, at vi skal omdirigere alt post til
tip@thisisodense.dk - for det tror jeg slet ikke vi kan gøre til messenger,
men det skal selvfølgelig skrives i autosvaret at mailen aldrig vil blive
tjekket igen.
Jeg mener bare, at vi skal droppe linket til tipmailen og til
tip-formularen i podio og bare lade alle henvendelser gå til vores
messenger.

2017-01-16 11:12 GMT+01:00 Morten Vestergaard Hansen <
notifications@github.com>:

**Comment by terkelskibbylarsen** [comment]
Man skal være logget ind for at skrive på Messenger, så vi ved hvem der skriver.
Derudover har man mulighed for at blokerer en bruger.

**Comment by terkellarsen** [comment]
Fixet dev.
Linket er ændret i koden, men da den laver en 301-redirect bliver det cachet voldsomt i browseren.
