### ISSUE TITLE
Data mangler i visning Recommendation repository

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#54]
![recommendations repository](https://cloud.githubusercontent.com/assets/23633076/22669014/225a2f70-ecc3-11e6-9f12-24635b71d1af.PNG)

**Comment by terkellarsen** [comment]
Det er en generel fejl i custom listview. Det samme gælder location og writers.
Jeg har prøvet at slette custom viewet og oprette det igen uden det hjalp.
Sitet er blevet opdateret til 7.5.9 inden for de sidste par dage, så mit bud er at det bliver fixet når der kommer ny version d. 21/2. Det er nok ikke en god ide at nedgradere.

**Comment by kristianbanghansen** [comment]
List viewet er nu udfyldt igen. Jeg lukker dette issue.

**Comment by terkelskibbylarsen** [comment]
Kolonnerne bliver kun udfyldt hvis antal viste items per side i listen oversiger totalt antal. Nu vises 5000 per side, så fejlen er ikke rettet.
