### ISSUE TITLE
KRITISK FEJL: MultiNode TreePicker - Location

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#62]
![udklip343434](https://cloud.githubusercontent.com/assets/23633076/23354178/34b9c604-fcd0-11e6-8354-a680f9fbba2d.PNG)

**Comment by kristianbanghansen** [comment]
@mimse @terkellarsen @terkelskibbylarsen

**Comment by terkelskibbylarsen** [comment]
Fixet

**Comment by kristianbanghansen** [comment]
Fedt!

**Comment by kristianbanghansen** [comment]
Jeg opdagede også lige denne artikel:
http://issues.umbraco.org/issue/U4-9183

**Comment by terkelskibbylarsen** [comment]
Listen er stadig tom som default. men der kommer locations frem ved søgning.
