### ISSUE TITLE
Lille rettelse af billedetekst på skribentprofilerne 

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#64]
På skribentprofilerne skal billedeteksten rettes. 
- [ ] Erstat teksten "Skribent siden" med GetDictionaryValue("Medlem siden")

Screenshot:
![Medlemsidenx](https://user-images.githubusercontent.com/23633076/59164521-4da56a00-8b0e-11e9-9f7f-e3823f28114f.JPG)

Dictionaryvalue er oprettet i dev

**Comment by mimse** [comment]
Fixed
