### ISSUE TITLE
Upload af medier virker ikke

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#65]
Det er ikke muligt at uploade billeder til mediearkivet. Upload-funktionen i Media Picker virker heller ikke Rich Text Editor (se billedet).

Dette er en afgørende funktion for at kunne lancere blogindlæg/longreads.

![udklipsdsdsdsds](https://cloud.githubusercontent.com/assets/23633076/23374226/9a78e120-fd23-11e6-88d9-d4d6992bc1e2.PNG)

**Comment by terkelskibbylarsen** [comment]
Det virker hvis du laver en mappe og derefter drag/dropper ind i den

**Comment by kristianbanghansen** [comment]
Ah, got it!
