### ISSUE TITLE
Fjernelse af "Døre åbnes" både i frontend og backend

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#68]
"Døre åbnes"-feltet fortsætter med at blive autoudfyldt med eventets starttidspunkt - også selvom feltet er lagt over i "info"-fanen istedet for "content"-fanen.
Derfor mener jeg, at vi må tage konsekvensen og fjerne feltet helt - både backend og frontend. Så vigtigt er det heller ikke.

![udklip32233232](https://cloud.githubusercontent.com/assets/23633076/23591840/020787c4-01f7-11e7-840e-bec10470e087.PNG)

**Comment by kristianbanghansen** [comment]
@mimse @terkelskibbylarsen Denne rettelse er højt prioriteret. Det bliver ved med at fremgå på hjemmesiden, selvom skribenterne ikke indtaster noget i feltet.

**Comment by mimse** [comment]
@kristianbanghansen, du har broken socialpost ved at fjerne feltet

**Comment by mimse** [comment]
Har tilføjet feltet igen til prod

**Comment by kristianbanghansen** [comment]
@mimse Kan vi ikke gøre noget ved det? Der er ingen, der bruer feltet, og alt data, der er indtastet i det, er ligegyldigt. Nu skal jeg ind og slette alle tidspunkterne manuelt.

**Comment by mimse** [comment]
@kristianbanghansen Jeg skal ind og fjerne der hvor flettet bruges i koden inden vi fjerne det i Umbraco. Skal jeg nok gør i aften.
