### ISSUE TITLE
Rette fejl i SocialPosts til locations

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#70]
Linket "www.thisisodense.dk/places" skal rettes til "www.thisisodense.dk/da/places". Ellers melder siden en runtime error.

Alternativt skal der oprettes en automatisk redirect fra den ene side til den anden.

**Comment by kristianbanghansen** [comment]
![fejl i locations socialpost](https://user-images.githubusercontent.com/23633076/48319425-34871a00-e60e-11e8-965f-04e2486cd751.PNG)

@mimse Kan du rette denne fejl hurtigst muligt. Pil er begyndt at poste byguide-opslag jævnligt på facebook, og det er en irriterende ting at skulle huske at rette hver gang.

**Comment by mimse** [comment]
Skal jeg se hvad jeg kan gøre

**Comment by mimse** [comment]
Det er nu rettet
