### ISSUE TITLE
Artikler i bloggen skal sorteres efter "udgivelsesdato"

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#77]
Lige nu sorteres blogartiklerne efter den oprettelsesdato, som Umbraco selv genererer. Istedet skal artiklerne sorteres efter den udgivelsesdato, vi selv definerer i artiklen. Nyeste først, ældste sidst..
![edssdsssn](https://cloud.githubusercontent.com/assets/23633076/25089113/8ba70bf8-237b-11e7-90c8-5e326e30f20b.png)

**Comment by mimse** [comment]
@kristianbanghansen det syntes jeg da også den gør?

**Comment by kristianbanghansen** [comment]
Det virker. Også i live.

**Comment by kristianbanghansen** [comment]
Det virker i dev, men ikke i live.

**Comment by kristianbanghansen** [comment]
@mimse FORKLARING: Fejlen opstår, fordi det kun er de enkelte sider, der sorterer decending efter udgivelsesdato. Den samlede liste sorterer ascending efter ID. Derfor ser sorteringen også ud til at virke i dev (selvom den ikke gør det), fordi de er oprettet i én bunke, så deres ID'er er tildelt i omvendt rækkefølge.

**Comment by mimse** [comment]
Jeg syntes det ligner det fungere nu :-)
