### ISSUE TITLE
Liste/arkiv-side under hver skribent

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#81]
Jeg har nu designet listevisningen af skribenters gamle anbefalinger/artikler i html. Hent koden her, og se illustrationerne:
[list-view html.txt](https://github.com/thisisodense/tio-web/files/949767/list-view.html.txt) (inkl. den relevante css, der er tilpasset siden)

Desktop:
![list view 680plus top](https://cloud.githubusercontent.com/assets/23633076/25314280/6f2c3c76-2841-11e7-8a33-feffa8a188ab.PNG)
![list view 680plus bund](https://cloud.githubusercontent.com/assets/23633076/25314283/76b9c238-2841-11e7-9038-48dde1ecb0f2.PNG)

Mobil:
![list view 400minus top](https://cloud.githubusercontent.com/assets/23633076/25314300/a3e56988-2841-11e7-8a3e-57d96f6f4d41.PNG)
![list view 400minus bund](https://cloud.githubusercontent.com/assets/23633076/25314302/a8d8d1be-2841-11e7-86a4-35bffbf34563.PNG)

@terkellarsen @terkelskibbylarsen

**Comment by mimse** [comment]
Skal den erstatte http://www.thisisodense.dk/writer/1094/anders-skovgaard? Eller det en helt ny side?
Hvis ja hvor skal der så linkens til den?
Hvis ikke, hvor skal beskrivelsen af forfatteren så stå?

**Comment by kristianbanghansen** [comment]
Det skal i URL'en fremgå som en underside til skribentprofilen, dvs. "www.thisisodense.dk/writer/1094/anders-skovgaard/archive". Man kan navigere ind til den på 2 måder:

1) Under skribentens billede kan man klikke sig ind til 3 forskellige filtrerede visninger af skribentens arkiv: Anbefalinger, artikler eller steder. URL'en på landingssiderne er fx "www.thisisodense.dk/writer/1094/anders-skovgaard/archive/2/articles"
![links til skribentarkiv](https://user-images.githubusercontent.com/23633076/50930746-16e4fe00-1461-11e9-864a-9307b10b2f74.PNG)

2) I bunden af skribentens profiltekst kan man klikke sig ind til en ufiltreret visning af skribentens arkiv. Altså anbefalinger, artikler og steder samlet og sorteret efter nyeste først.
![link til skribentarkiv](https://user-images.githubusercontent.com/23633076/50930821-472c9c80-1461-11e9-8fe3-d98a76c5df68.PNG)
