### ISSUE TITLE
Forkerte overskrifter i googles søgeresultat

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#82]
Den sidetitel, som blot burde gælde for forsiden, bliver ved en fejl overført til alle artiklerne også.
![forkerte overskrifter i google](https://user-images.githubusercontent.com/23633076/28005617-ed83fa4a-654b-11e7-8f28-42568d7e74f2.PNG)

@mimse @terkelskibbylarsen @terkellarsen

**Comment by mimse** [comment]
Fixed and deployed
