### ISSUE TITLE
Tag-manager virker ikke

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#84]
...og tags i nogle af artiklerne er brudt op i enkeltbogstaver uden mulighed for tilføjelse af nye.

![tagmanager](https://user-images.githubusercontent.com/23633076/50742347-10107e00-120a-11e9-8db0-2df0117d7aa2.PNG)

![tags](https://user-images.githubusercontent.com/23633076/50742350-130b6e80-120a-11e9-9c2a-bee0b9c1b566.PNG)

**Comment by mimse** [comment]
Jeg har rettet den ene ting med at tags står som bogstaver. Men at tag manageren ikke viser noget kan jeg ikke rigtig gør noget ved. Den gik i stykker da vi opdaterede umbraco til den nyeste version desværre
