### ISSUE TITLE
Bottom Writer Box på recommendation detaljeside

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#88]
- [x] I bunden af anbefalinger (detaljeside) erstattes kommentarfeltet med en "Bottom Writer Box"
- [x] Den trækker tekst fra writer-beskrivelsen (ligesom arkiv-siderne).
- [x] Den viser skribentbilledet (ligesom writerOfWeek-boksen på forsiden)
- [x] Den linker til hhv. skribentprofilen og skribentarkivet.
- [x] På forsidevisningen af anbefalinger skal der ikke en BottomWriterBox. 
- [x] På forsidevisningen af anbefalinger skal facebook-kommentarfeltet slettes.
- [ ] Tekstuddrag fra writer-beskrivelsen skal være 200 tegn.

Screenshot:
![BottomWriterBox](https://user-images.githubusercontent.com/23633076/59253461-918f9080-8c2e-11e9-8a00-5375dd9e71c0.JPG)

Kode:
[WriterAnbefalingbund (1).txt](https://github.com/thisisodense/tio-web/files/3286280/WriterAnbefalingbund.1.txt)

Styling og ordbog er på plads i dev.

**Comment by mimse** [comment]
@kristianbanghansen ligger på dev nu

**Comment by kristianbanghansen** [comment]
Fedt @mimse ! Det er tæt på :-)

De ting, jeg har markeret med gult her, var dog ikke en del af min kode. Er det muligt at fjerne dem? Fx strippe teksten for dens p-tags, inden den bliver indsat?

![Udkldsdsdsdsdsip](https://user-images.githubusercontent.com/23633076/59793056-e76ed300-92d5-11e9-9ddb-55b2888575e6.JPG)

**Comment by kristianbanghansen** [comment]
Det er tæt på. Der er lige lidt flere p-tags, end jeg forventede, men prøver lige at style mig ud af det.

Én ting, du gerne må gøre er dog at fjerne linket "TIL FORSIDEN".

**Comment by mimse** [comment]
Men skal den ikke være på detail siden mere?

**Comment by mimse** [comment]
Jeg kan måske godt fjerne <p> tags, de kommer dog fra tekst editoren i umbraco

**Comment by kristianbanghansen** [comment]
Egentlig er der allerede et link til forsiden. Det får man, hvis man trykker på "UGENS EVENTS". Så der er ikke brug for "TIL FORSIDEN" mere.

**Comment by kristianbanghansen** [comment]
Jeg er ved at lave en løsning med styling af de p-tags, så du ikke behøver at fjerne dem.

**Comment by kristianbanghansen** [comment]
![Udksddsdslip](https://user-images.githubusercontent.com/23633076/59794267-e0958f80-92d8-11e9-9da2-5cd719e85626.JPG)

Så er det løst med styling.

**Comment by kristianbanghansen** [comment]
Linket "Til Forsiden" er der stadig hos mig, selvom jeg har trykket "tøm cache og genindlæs fuldstændig"

Vil du forresten lige tjekke URL på de to links til writer og writerArchive, da det ligner, at de bruger ID'et fra anbefalingen istedet for skribentens ID.

@mimse

**Comment by mimse** [comment]
Det skulle nu være rettet @kristianbanghansen

**Comment by kristianbanghansen** [comment]
Super, tak @mimse 

...ÈN sidste ting. Kan jeg få antal tegn i tekstuddraget ned på 175 (inkl. mellemrum)? Det vil gøre, at den holder sig på 3 linjer i mobilvisningen.

**Comment by kristianbanghansen** [comment]
OBS: Det er kun detaljesiderne, at denne BottomWriterBox skal på. Ikke på forsiden.

**Comment by mimse** [comment]
![image](https://user-images.githubusercontent.com/1250254/59831364-ee332f80-9341-11e9-820b-535e6ecf0c2c.png)

Ser lidt funky ud når der ingen beskrivelse er

**Comment by kristianbanghansen** [comment]
Ja, det skal Isaac lige ind og rette op på.

**Comment by mimse** [comment]
Så skulle den være på plads :-)

**Comment by kristianbanghansen** [comment]
TAK! :-D
Nu er jeg endelig færdig med stylingen. Vil du sætte antal tegn op til 200? Nu er der plads igen. Og så deploye til live.

**Comment by kristianbanghansen** [comment]
Alt er færdigt. Der mangler kun at få tegnantallet op på 200 igen. Og det er ikke en haster.

**Comment by mimse** [comment]
tegn antal 200 :-)
