### ISSUE TITLE
Location-arkiv

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#90]
Location-arkiver er mere simple end skribentarkiverne.

- [x] Viser alle de recommendations, der er tilknyttet pågældende location. Altså recommendations er den eneste content-type.
- [x] Udover små justeringer skal opsætningen være helt den samme som skribent-arkiverne.
- [x] Billedet trækkes fra location og linker til location
- [x] I den røde tekstboks trækkes indhold fra LongDescription fra pågældende location
- [x] Linket til "x anbefalinger" under den røde boks skal pege på side 1 af det pågældende location-arkiv. Det har altså kun effekt, hvis man er på side 2 eller flere af locations-arkivet.
- [x] Recommendations skal være sorteret efter startdato. Nyeste først.
- [x] URL skal være fx "/placeArchive/4804/studiestuen"
- [ ] Visning af billede og tekstboks skal være anderledes for locations, der ikke er offentliggjort i byguiden.

Screenshot:
![Udklipdfdfgdfgdf](https://user-images.githubusercontent.com/23633076/59331569-8ef76e80-8cf4-11e9-9526-cd244a46ce6d.JPG)

Kode:
[locationarchive (1).txt](https://github.com/thisisodense/tio-web/files/3324062/locationarchive.1.txt)

Styling og ordbog er på plads i dev.

**Comment by mimse** [comment]
Hvordan kommer man til location arkivet?

**Comment by kristianbanghansen** [comment]
Man kommer til location-arkivet ved at klikke på knappen "Vores x anbefalinger i "bottomwriterbox på location" jf. #91 og ved klik på "x anbefalinger" i billedeteksten på locations.

![Uererererdklip](https://user-images.githubusercontent.com/23633076/59999427-3a43e400-9662-11e9-995f-2ec25dfe8b6c.JPG)

**Comment by mimse** [comment]
Er dette ikke location arkivet? 

http://www.thisisodense.dk/writerArchive/1094/anders-skovgaard/Locations#.XRCBapMzbUI

**Comment by kristianbanghansen** [comment]
Nej, det er skribentarkivet (som viser alle de recommendations, articles og locations, der er tilknyttet skribenten).
Location-arkivet skal vise alle de recommendations, der er tilknyttet pågældende location.

**Comment by kristianbanghansen** [comment]
Har lige lavet en lille rettelse til koden. Der manglede lige et br-tag som afslutning på navigationen.

**Comment by mimse** [comment]
inde i <nav></nav> eller lige efter?

**Comment by kristianbanghansen** [comment]
Nej, lige inden div class="navigation" bliver afsluttet. 
Dvs. lige efter /ul og lige før /div. Der har jeg indsat et br style="clear:both;"

Det er indsat i min kode-fil her på issuet

**Comment by mimse** [comment]
Hov, troede det var et andet issue vi talte om :-)

**Comment by mimse** [comment]
Hvorfor skal man kunne klikke på 100 anbefalinger?

**Comment by kristianbanghansen** [comment]
Godt set. Det tjener ikke noget formål som link. For den linker på til den side, man allerede er på. Jeg har vel bare bevaret linket af hensyn til stylingen. Men jeg kan nok sagtens style den tekst, uden at det er et link.

**Comment by kristianbanghansen** [comment]
Det bliver kompliceret at style det om til almindelig tekst, så behold det som link. 

Linket skal pege på fx "/locationArchive/2149/papas-papbar/Recommendations". Altså på første side af det pågældende location-arkiv. Man kan således bruge linket til at komme hurtigere tilbage til første side, hvis man er på fx side 4.

**Comment by kristianbanghansen** [comment]
jeg håber det svarede på spørgsmålet. Skriv, hvis der er andet, du er i tvivl om. @mimse

**Comment by kristianbanghansen** [comment]
Super fedt! Og velkommen tilbage fra forældreorlov.
Jeg havde glemt at skrive "nyeste først" ved sortering af anbefalingerne. Lige nu sorterer den med "ældste først". Ellers virker alt perfekt.

**Comment by mimse** [comment]
Prøv igen :-)

**Comment by kristianbanghansen** [comment]
Fedt, det virker... Men... jeg har opdaget, at de locations, der ikke er i byguiden - og som derfor ikke har billeder og beskrivelse, viser en fejlmeddelelse. Så der er lige en ekstra opgave med det.

**Comment by mimse** [comment]
Har du et eksempel? Og skal man stadig kunne se den?

**Comment by kristianbanghansen** [comment]
Reglen skal være, at hvis denne knap ikke er valgt på en location, så skal der 

- ikke vises brødtekst i det røde felt. Kun stedets titel/link. 

- ikke vises location-billedet, men på samme plads i stedet vise det skiftende logo-billede vi har som standard i vores sidehovede.

![Ussdsdsddklip](https://user-images.githubusercontent.com/23633076/63158029-a9add280-c018-11e9-8273-358c013d3e26.JPG)

Eksempel på location, der ikke har beskrivelse og billede, og som ikke er i byguiden her: http://dev-this-is-odense.s1.umbraco.io/da/placeArchive/5084/syddansk-musikkonservatorium

Eksempel på location, der har gammelt billede og tekst liggende, men som er fravalgt til byguiden: http://dev-this-is-odense.s1.umbraco.io/da/placeArchive/5095/kulturmaskinen

**Comment by kristianbanghansen** [comment]
@mimse Sig til, hvis jeg skal forklare det bedre. Har du et andet forslag til en mere simpel løsning, er jeg også meget åben for det.

**Comment by mimse** [comment]
Prøv igen

**Comment by kristianbanghansen** [comment]
Fantastisk! Det virker! Rul ud! :-D
