### ISSUE TITLE
Gæsteanbefalinger har Runtime Error på detaljesider

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#93]
Når en recommendation har udfyldt checkbox i fanen "Guest Writer", så laver siden Runtime Error.

Det er altså ikke muligt at læse gæsteanbefalinger som detaljeside på hjemmesiden.

Se eksempel i backend her: http://www.thisisodense.dk/umbraco/#/content/content/edit/1434
og på hjemmesiden her: http://www.thisisodense.dk/da/1434/tag-paa-festival-paa-fyn

Checkbox her:
![Udklipdfdfdfdfdf](https://user-images.githubusercontent.com/23633076/59906946-34ec5c80-940a-11e9-99e8-0b8122e9e9f7.JPG)

Screenshot her:
![Udklidfdfdfdfdfdfp](https://user-images.githubusercontent.com/23633076/59906693-a11a9080-9409-11e9-85bf-00ee61a19cbd.JPG)

**Comment by mimse** [comment]
![image](https://user-images.githubusercontent.com/1250254/59922820-ebb00300-9431-11e9-9627-8feac7384351.png)

Hvordan skal det se ud når det er en gæst?

**Comment by mimse** [comment]
Never mind, det var et forkert id jeg bruge

**Comment by mimse** [comment]
Fixed
