### ISSUE TITLE
Fejl i sidetitel på arkivsider og skribentsider (metadata)

### ISSUE THREAD

**Issue by kristianbanghansen** [thisisodense/tio-web#98]
"head --> title" på arkivsider og skribentprofil lægger en overflødig bindestreg og mellemrum ind før sidens titel.

- Fx skribentprofil: http://www.thisisodense.dk/writer/1219/pil-lindgreen = "- Pil Lindgreen"
- Fx skribentarkiv: http://www.thisisodense.dk/writerArchive/1219/pil-lindgreen = "- Pil Lindgreen"
- Fx location-arkiv: http://www.thisisodense.dk/da/placeArchive/1108/teater-momentum "- Teater Momentum"

Det får både google-resultater og facebook-linkvisninger til at se lidt ufærdige ud.

- [x] "- " skal fjernes fra title
- [x] på skribentprofiler skal i stedet stå i "title": Skribentnavn - Umbraco.GetDictionaryValue("Sker der noget i Odense?")
- [x] på skribentarkiver skal i stedet stå i "title": Skribentnavn - Umbraco.GetDictionaryValue("Mine andre anbefalinger")
- [x] på locationarkiver skal i stedet stå i "title": Locationnavn - This Is Odense -Umbraco.GetDictionaryValue("Vores") Umbraco.GetDictionaryValue("recommendations")

**Comment by mimse** [comment]
@kristianbanghansen fejl er blevet rettet :-)
